### ISSUE TITLE
There needs to be a Dockerfile in the current directory

### ISSUE THREAD

**Issue by Sohaib12** [mickep76/docker-build-ami#2]
When I run the docker-build-ami, I get this error, I also put a simple Dockerfile in there with just the following lines:

FROM ubuntu:14.04

RUN apt-get update && apt-get install -y unzip
RUN apt-get update && apt-get install -y nano

But I am still getting this error.

**Comment by ake-persson** [comment]
Your ticket doesn't include an error message?

Also be aware that you need to specify which AMI image to base your Host image on, i.e. FROM is ignored.

**Comment by ake-persson** [comment]
```
  -i, --image-id        Source AMI image ID
```

**Comment by Sohaib12** [comment]
The error message was: "There needs to be a Dockerfile in the current directory" but I found the solution for it. Now I want to know if I have to have an existing AMI image to be able to run it? 

Actually what I am trying to do is to run a docker file as soon as I create an Amazon EC2 instance. I want to automate this whole process. I could write a script that can fire up an Amazon Instance. I actually want to run Docker "as" an instance. Is this a good alternative?

**Comment by ake-persson** [comment]
AWS natively supports Docker, alt. you can build an AMI image that start's docker on boot and then take your Dockerfile as an argument. This can be done with cloud init.

This project is mainly focused on building AMI images using Dockerfile as the template, similar to Packer.

**Comment by ake-persson** [comment]
Non-issue
